### ISSUE TITLE
Not translated

### ISSUE THREAD

**Issue by YiffyToys** [magepow/magento-2-categories#10]
https://github.com/magepow/magento-2-categories/blob/master/view/frontend/templates/categories.phtml#L57
hardcodes "show now" in English.

Either that string should be translatable or a string setting in the admin page.
At the very least it should be possible to switch it off.

**Comment by YiffyToys** [comment]
Will there be a release?
Last release was 11th of May and this fix was 28th of June.

**Comment by magiccart** [comment]
Hi, Ok done!
