### ISSUE TITLE
Bloch widget for change position in home page

### ISSUE THREAD

**Issue by Danieleeffe1** [magepow/magento-2-categories#13]
Hello everybody

Is it possible to load the module on the home page from the static block?
exemple
{{block class="Magepow\Categoryes\Block\Widget" }}

if so what is the code?

thank you

**Comment by magiccart** [comment]
Yes, You can add something like example here

{{Block class="Magepow\Categories\Block\Widget\Categories" title="Magepow Categories Widget" subtitle="Magepow Categories Widget" template="categories_widget.phtml" sort_attribute="name" description="1" thumbnail="1" item_amount="1" categories="25,11" slide="1" vertical="false" infinite="true" autoplay="true" arrows="true" dots="false" speed="300" autoplaySpeed="3000" padding="15" rows="1" mobile="1" portrait="1" landscape="2" tablet="3" notebook="3" laptop="4" desktop="4" widescreen="4" visible="5"}}

**Comment by Danieleeffe1** [comment]
wow! thank you...

How much text.

you could insert a tools that prints this code inside the module to copy and paste the code, what do you think?

**Comment by magiccart** [comment]
Do you mean code add examples to guide? Can you send an example will good?
I think is a good idea!

**Comment by Danieleeffe1** [comment]
I'm not a programmer, I can tell you where I found similar tools

I have installed a MagePlaza module that administers banners / slides that provides the static block code as an alternative to selecting the product page / product category or home page.

I find this option very convenient to have more control over home page design with standard Magento tools
