### ISSUE TITLE
Categories Layout Grid not working only list

### ISSUE THREAD

**Issue by acc1986** [magepow/magento-2-categories#5]
I installed via composer and is working except the Categories Layout: Grid option. It lists all the categories fine tho. Is there anything specific i need to set in the category page under Design tab? I have tried altering the layout between 1, 2 & 3 column's but no difference still just lists with a bullet point.

**Comment by magepow** [comment]
Hi, We will check and update soon.

**Comment by magepow** [comment]
Hi, I have fixed and updated to the new version, you can run 2 commands below to install the new version.
composer remove magepow/categories
composer require magepow/categories
