### ISSUE TITLE
Placeholder custom in system config not work, always magento placeholder

### ISSUE THREAD

**Issue by ximenez** [magepow/magento-2-categories#7]
I change vendor\magepow\categories\Block\Categories.php to add helper image in construct:
...
\Magento\Catalog\Helper\Image $helperImage
...
$this->helperImage  = $helperImage;

and I change function getImage to get placeholder success:
$placeholderImageUrl = $this->helperImage->getDefaultPlaceholderUrl('small_image');

File result:

`<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:04:26
 */

namespace Magepow\Categories\Block;

class Categories extends \Magento\Framework\View\Element\Template
{
    const XML_PATH = 'category_page'; 
    
    public $helper;

    public $storeManager;

    public $helperImage;
    
    public $coreRegistry;

    public $categoryFactory;

    public $catalogHelperOutput;
    
    public function __construct(
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\Framework\Registry $coreRegistry,
        \Magento\Catalog\Model\CategoryFactory $categoryFactory,
        \Magento\Catalog\Helper\Output $catalogHelperOutput,
        \Magento\Catalog\Helper\Image $helperImage,
        \Magepow\Categories\Helper\Data $helper,
        \Magento\Framework\View\Element\Template\Context $context,
        array $data = []
    ) {    
        $this->storeManager        = $storeManager;
        $this->coreRegistry        = $coreRegistry;
        $this->categoryFactory     = $categoryFactory;
        $this->catalogHelperOutput = $catalogHelperOutput;
        $this->helperImage  = $helperImage;
        $this->helper = $helper;
        parent::__construct($context, $data);
    }

    public function getLayout() 
    {
        return $this->helper->getConfig(self::XML_PATH . '/layout');
    }

    public function getHeading() 
    {
        return $this->helper->getConfig(self::XML_PATH . '/heading');
    }    

    public function isShowDescription() 
    {
        return $this->helper->getConfig(self::XML_PATH . '/description');
    }    

    public function getSortAttribute() 
    {
        return $this->helper->getConfig(self::XML_PATH . '/sort_attribute');
    } 

    public function getExcludeCategory()
    {
        return $this->helper->getConfig(self::XML_PATH . '/exclude_category');
    }

    public function getCategories()
    {

        $category = $this->coreRegistry->registry('current_category');
        if(!$category) return;

        $categoryId = $category->getId();

        if ($this->isExcluded($categoryId)) return;

        $sortAttribute = $this->getSortAttribute();  
        $model = $this->categoryFactory->create();
        $categories = $model->getCollection()
        ->addAttributeToSelect(['name', 'url_key', 'url_path', 'image','description'])
        // ->addAttributeToFilter('include_in_menu', 1)
        ->addAttributeToFilter('parent_id', $categoryId)
        ->addAttributeToSort($sortAttribute)
        ->addIsActiveFilter();

        return $categories;
    }

    public function getDescription($category)
    {
        $description = $category->getDescription();
        if ($description) {
            $categoryDescription = $this->catalogHelperOutput
            ->categoryAttribute($category, $description, 'description');
        } else {
            $categoryDescription = '';
        }
        return trim($categoryDescription);
    }

    public function getImage($category)
    {
		$placeholderImageUrl = $this->helperImage->getDefaultPlaceholderUrl('small_image');
        $image = $category->getImage();
        if ($image != null) {
            $url = $this->getImageUrl($image);
        } else {
            $url = $placeholderImageUrl;
        }  
        return $url;
    }
    
    public function getImageUrl($image)
    {
        $url = false;  
        if ($image) {
            if (substr($image, 0, 1) === '/') {
                $url = $this->storeManager->getStore()->getBaseUrl(
                    \Magento\Framework\UrlInterface::URL_TYPE_WEB
                ) . ltrim($image, '/');
            } else {
                $url = $this->storeManager->getStore()->getBaseUrl(
                    \Magento\Framework\UrlInterface::URL_TYPE_MEDIA
                ) . 'catalog/category/' . $image;
            }
        } 
        return $url;
    }
    
    public function isExcluded($id)
    {
        $excluded = explode(',', $this->getExcludeCategory());
        if (!$excluded) return;
        return in_array($id, $excluded);
    }
}`

**Comment by magiccart** [comment]
@ximenez Thanks for contributing
