### ISSUE TITLE
Sorting by position does not give ideal sorting result

### ISSUE THREAD

**Issue by ProxiBlue** [magepow/magento-2-categories#8]
The sot by just position does not take into consideration the parent child setup of categories in the positional tree.

For example:

![image](https://user-images.githubusercontent.com/4994260/117545573-f2ad8200-b058-11eb-8018-405c3d4f62cb.png)

Here category with ID 94 will be positioned before category with ID 71, even though category with ID 94 is way lower (and a child of another parent category.

Ideally the position sorting shoudl consider teh parent to child layout as well.

**Comment by ProxiBlue** [comment]
The result can be improved by adding parent_id into the sort, thus allowing the position to be calculated on the parent value, this ordering parent categories first, followed by the position of children

parent_id, position

**Comment by ProxiBlue** [comment]
Even though adding parent_id gave more ideal sorting (brining top level categories to the front), it was still not as accurate as I would have liked.
Sorting by CHAR_LENGTH of the path field brings a better result when also sorting by position

**Comment by magiccart** [comment]
@ProxiBlue You please try with code below

        $sortAttribute = $this->getSortAttribute();
        $model = $this->categoryFactory->create();
        $categories = $model->getCollection()
        ->addAttributeToSelect(['name', 'url_key', 'url_path', 'image','description'])
        ->addAttributeToFilter('parent_id', $categoryId)
        ->addIsActiveFilter();

        if( $sortAttribute == "position" ) {
            $categories->addAttributeToSort('level');
        }

        $categories->addAttributeToSort($sortAttribute);

**Comment by ProxiBlue** [comment]
Hey,

Yes, level works just as good, and is less complicated code, missed that one :)
Results are the same as the code I proposed.

**Comment by magiccart** [comment]
I have updated it. Thanks

**Comment by magiccart** [comment]
Just note :)
$sortAttribute = $this->getSortAttribute();

$categories = $this->categoryFactory->create()->getCollection()
			        ->addAttributeToSelect(['name', 'url_key', 'url_path', 'image','description'])
			        ->addAttributeToFilter('parent_id', $categoryId)
			        ->addIsActiveFilter();

if($sortAttribute  == "position") {
    // for position also sort by length of the category pah so as to order by parents first, then the children
    // ref https://github.com/magepow/magento-2-categories/issues/8
    $categories->getSelect()->order(
        new \Zend_Db_Expr("CHAR_LENGTH(path), $sortAttribute")
    );
} else {
    $categories->addAttributeToSort($sortAttribute);
}
